config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "about-me", to: "static_pages#about"
  get "emoticons", to: "static_pages#emoticon"
  get "favorite-songs", to: "songs#songs"

  resources :posts, param: :slug do
    member do
      put :vote
      put :unvote
    end
  end
  resources :tags, param: :slug, only: %i(show)
  resources :songs, except: :destroy
  resources :skills

  match "/404", to: "errors#render404", via: :all
  match "/422", to: "errors#render422", via: :all
  match "/500", to: "errors#render500", via: :all
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name, :percent, :skill_type, presence: true
  validates :percent,
            numericality: { greater_than_or_equal_to: 0,
                            less_than_or_equal_to: 100,
                            only_integer: true }

  enum skill_type: { language: 0, technology: 1 }
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :raise_not_found
  before_action :load_skill, only: %i(edit update destroy)

  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new skill_params

    respond_to do |format|
      @skill.save
      load_data
      format.js
    end
  end

  def edit; end

  def update
    respond_to do |format|
      @skill.update skill_params
      load_data
      format.js
    end
  end

  def destroy
    respond_to do |format|
      @skill.destroy
      load_data
      format.js
    end
  end

  private

  def skill_params
    params.require(:skill).permit :name, :percent, :skill_type
  end

  def load_skill
    @skill = Skill.find params[:id]
  end

  def load_data
    @skill_language = Skill.language
    @skill_technology = Skill.technology
  end
end

app/views/skills/_form.html.slim
= form_for skill, remote: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control", required: true,
      autocomplete: "off"
  .form-group.mt-3
    = f.label :percent
    = f.number_field :percent, class: "form-control",
      max: 100, min: 0, required: true, autocomplete: "off"
  .form-group.mt-3
    = f.label :skill_type
    = f.select :skill_type,
      options_for_select(Skill.skill_types.map { |k, _| [k.capitalize, k] }, skill.skill_type),
      {}, { class: "form-control" }
  = f.submit "Save", class: "btn mt-3 skill-action-btn"

app/views/skills/_list_skill.html.slim
table.table.text-center.skill-table
  thead
    tr
      th scope="col" Name
      th scope="col" Percent
      th scope="col" Type
      th scope="col" colspan="2" Action
  tbody#list-skills
    - skills.each do |skill|
      = render "skill_item", skill: skill

app/views/skills/_skill_item.html.slim
tr id="skill-#{skill.id}"
  td = skill.name
  td = skill.percent
  td = skill.skill_type&.capitalize
  td = link_to "Edit", edit_skill_path(skill), class: "text-decoration-none", remote: true
  - if skill.technology?
    td = link_to "Delete", "javascript:void(0)",
      class: "text-decoration-none", id: "delete-skill-#{skill.id}", url: skill_path(skill)
  - else
    td.text-secondary.skills__delete_btn
      span Delete

app/views/skills/_skill_item_modal.html.slim
#skill-item.modal.fade.skill-item-modal tabindex="-1" aria-labelledby="skill-item-label" aria-hidden="true"
  .modal-dialog.modal-dialog-centered
    .modal-content
      .modal-header
        h5#skill-item-label.modal-title
        button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
      .modal-body
        #skill-item-body

app/views/skills/_skill_modal.html.slim
#skills-list.modal.fade.skill-modal tabindex="-1" aria-labelledby="skills-list-label" aria-hidden="true"
  .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
    .modal-content
      .modal-header
        h5#skills-list-label.modal-title Skills list
        button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
      .modal-body
        = link_to "New skill", new_skill_path, class: "btn float-end new-skill-btn", remote: true
        #skills-list-body

app/views/skills/create.js.slim
| $("#skill-item").modal("hide");
| $("#skill-tech-box").html("
= j render 'shared/about/skill_tech', skill_technology: @skill_technology
| ");
| $("#list-skills").append("
= j render 'skill_item', skill: @skill
| ");

|
  Toast.fire({
    icon: "success",
    title: "Skill #{@skill.name} was created successfully!"
  });

app/views/skills/destroy.js.slim
| $("#skill-#{@skill.id}").remove();
| $("#skill-tech-box").html("
= j render 'shared/about/skill_tech', skill_technology: @skill_technology
| ");

|
  Toast.fire({
    icon: "success",
    title: "Skill #{@skill.name} was destroyed successfully!"
  });

app/views/skills/edit.js.slim
| $("#skill-item").modal("show");
| $("#skill-item-label").text("Edit skill");
| $("#skill-item-body").html("
= j render "form", skill: @skill
| ");

app/views/skills/index.js.slim
| $("#skills-list").modal("show");
| $("#skills-list-body").html("
= j render "skills/list_skill", skills: @skills
| ");

app/views/skills/new.js.slim
| $("#skill-item").modal("show");
| $("#skill-item-label").text("New skill");
| $("#skill-item-body").html("
= j render "form", skill: @skill
| ");

app/views/skills/update.js.slim
| $("#skill-item").modal("hide");
| $("#skill-tech-box").html("
= j render 'shared/about/skill_tech', skill_technology: @skill_technology
| ");
| $("#skill-#{@skill.id}").replaceWith("
= j render 'skill_item', skill: @skill
| ");

|
  Toast.fire({
    icon: "success",
    title: "Skill #{@skill.name} was updated successfully!"
  });