config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "about-me", to: "static_pages#about"
  get "emoticons", to: "static_pages#emoticon"
  get "favorite-songs", to: "songs#songs"

  resources :posts, param: :slug do
    member do
      put :vote
      put :unvote
    end
  end
  resources :tags, param: :slug, only: %i(show)
  resources :songs, except: :destroy
  resources :skills

  match "/404", to: "errors#render404", via: :all
  match "/422", to: "errors#render422", via: :all
  match "/500", to: "errors#render500", via: :all
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, :author, :url, :cover, presence: true

  def previous
    Song.where(["id < ?", id]).order(:id).last
  end

  def next
    Song.where(["id > ?", id]).order(:id).first
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :raise_not_found, except: %i(songs)
  before_action :authenticate_user!, except: %i(songs)
  before_action :load_song, only: %i(edit update)

  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new song_params

    respond_to do |format|
      @song.save
      format.js
    end
  end

  def edit; end

  def update
    respond_to do |format|
      @song.update song_params
      format.js
    end
  end

  def songs
    song_id = if params[:song_id].to_i > Song.last.id
                Song.first.id
              elsif params[:song_id].to_i.zero?
                Song.last.id
              else
                params[:song_id].to_i
              end
    song_id = nil if params[:song_id].blank?

    current_song = Song.find_by(id: cookies[:song_id])
    lastest_song = cookies[:song_id].present? ? current_song : Song.all.sample

    @song = Song.find_by(id: song_id) || lastest_song
  end

  private

  def song_params
    params.require(:song).permit :id, :name, :author, :url, :cover
  end

  def load_song
    @song = Song.find params[:id]
  end
end

app/views/songs/_form.html.slim
= form_for song, remote: true do |f|
  - if song.persisted?
    .form-group
      = f.label :id, "ID"
      = f.text_field :id, class: "form-control", disabled: true
  .form-group.mt-3
    = f.label :name
    = f.text_field :name, class: "form-control", required: true,
      autocomplete: "off"
  .form-group.mt-3
    = f.label :author
    = f.text_field :author, class: "form-control", required: true,
      autocomplete: "off"
  .form-group.mt-3
    = f.label :url, "Audio URL"
    = f.text_field :url, class: "form-control", required: true,
      autocomplete: "off"
  .form-group.mt-3
    = f.label :cover, "Cover URL"
    = f.text_field :cover, class: "form-control", required: true,
      autocomplete: "off"
  = f.submit "Save", class: "btn mt-3 save-song-btn"

app/views/songs/_list_song.html.slim
table#datatables.table.table-bordered.text-center.align-middle.list-song-table
  thead
    tr
      th scope="col" No.
      th scope="col" Name
      th scope="col" Author
      th scope="col" Audio
      th scope="col" Cover
      th scope="col" Action
  tbody#list-song
    - songs.each do |song|
      = render "song_item", song: song

javascript:
  $("#datatables").DataTable({
    pageLength: 10,
    columnDefs: [
      { orderable: true, targets: [0, 1, 2] },
      { orderable: false, targets: "_all" }
    ]
  });

app/views/songs/_song_frame.html.slim
- cookies[:song_id] = song.id

.playlist-frame
  header.area-header
    .cover
      img src="#{song.cover}"
      .shadow style="`background-image: url('#{song.url}');`"

  main.area-control
    section.control-name-artist
      .item.name.rows
        span = song.name

      .item.artist
        span = song.author

      .repeat
        img.repeat-btn.js--repeat src="https://res.cloudinary.com/phucdx/image/upload/v1626365020/wataridori/songs/white_hjd775.png" alt="" title="Repeat"

      .sound.d-flex.justify-content-end.align-items-center
        .progress.volume-progress.js--progress-volume.d-none
          .progress-bar.volume-slider.js--volume-slider role="progressbar" style="width: 0%" aria-valuemin="0" aria-valuemax="100"

        i.fa.fa-volume-up.js--volume aria-hidden="true" title="Sound"

    section.control-progress.js--control-progress ref="progress"
      .progress.seek-progress.js--progress-seek
        .progress-bar.progress-slider.js--progress-slider role="progressbar" style="width: 0%" aria-valuemin="0" aria-valuemax="100"

      .timer
        p.text.js--current-time 00:00
        p.text.js--total-duration NaN

    section.player-controls
      = link_to "javascript:void(0)", class: "player-controls__item prevNext js--prev-song",
        data: { id: song.id, url: favorite_songs_path } do
        svg.icon
          use xlink:href="#icon-prev"

      = link_to "javascript:void(0)", class: "player-controls__item playBtn js--playpause-track",
        data: { url: favorite_songs_path, audio: song.url } do
        svg.icon
          use.pause-song.d-none xlink:href="#icon-pause"
          use.play-song xlink:href="#icon-play"

      = link_to "javascript:void(0)", class: "player-controls__item prevNext js--next-song",
        data: { id: song.id, url: favorite_songs_path } do
        svg.icon
          use xlink:href="#icon-next"
  svg xmlns="http://www.w3.org/2000/svg" hidden xmlns:xlink="http://www.w3.org/1999/xlink"
    defs
      <symbol id="icon-pause" viewBox="0 0 32 32">
        <title>Pause</title>
        <path
          d="M16 0.32c-8.64 0-15.68 7.040-15.68 15.68s7.040 15.68 15.68 15.68 15.68-7.040 15.68-15.68-7.040-15.68-15.68-15.68zM16 29.216c-7.296 0-13.216-5.92-13.216-13.216s5.92-13.216 13.216-13.216 13.216 5.92 13.216 13.216-5.92 13.216-13.216 13.216z"
        ></path>
        <path
          d="M16 32c-8.832 0-16-7.168-16-16s7.168-16 16-16 16 7.168 16 16-7.168 16-16 16zM16 0.672c-8.448 0-15.328 6.88-15.328 15.328s6.88 15.328 15.328 15.328c8.448 0 15.328-6.88 15.328-15.328s-6.88-15.328-15.328-15.328zM16 29.568c-7.488 0-13.568-6.080-13.568-13.568s6.080-13.568 13.568-13.568c7.488 0 13.568 6.080 13.568 13.568s-6.080 13.568-13.568 13.568zM16 3.104c-7.104 0-12.896 5.792-12.896 12.896s5.792 12.896 12.896 12.896c7.104 0 12.896-5.792 12.896-12.896s-5.792-12.896-12.896-12.896z"
        ></path>
        <path
          d="M12.16 22.336v0c-0.896 0-1.6-0.704-1.6-1.6v-9.472c0-0.896 0.704-1.6 1.6-1.6v0c0.896 0 1.6 0.704 1.6 1.6v9.504c0 0.864-0.704 1.568-1.6 1.568z"
        ></path>
        <path
          d="M19.84 22.336v0c-0.896 0-1.6-0.704-1.6-1.6v-9.472c0-0.896 0.704-1.6 1.6-1.6v0c0.896 0 1.6 0.704 1.6 1.6v9.504c0 0.864-0.704 1.568-1.6 1.568z"
        ></path>
      </symbol>
      <symbol id="icon-play" viewBox="0 0 32 32">
        <title>Play</title>
        <path
          d="M21.216 15.168l-7.616-5.088c-0.672-0.416-1.504 0.032-1.504 0.832v10.176c0 0.8 0.896 1.248 1.504 0.832l7.616-5.088c0.576-0.416 0.576-1.248 0-1.664z"
        ></path>
        <path
          d="M13.056 22.4c-0.224 0-0.416-0.064-0.608-0.16-0.448-0.224-0.704-0.672-0.704-1.152v-10.176c0-0.48 0.256-0.928 0.672-1.152s0.928-0.224 1.344 0.064l7.616 5.088c0.384 0.256 0.608 0.672 0.608 1.088s-0.224 0.864-0.608 1.088l-7.616 5.088c-0.192 0.16-0.448 0.224-0.704 0.224zM13.056 10.272c-0.096 0-0.224 0.032-0.32 0.064-0.224 0.128-0.352 0.32-0.352 0.576v10.176c0 0.256 0.128 0.48 0.352 0.576 0.224 0.128 0.448 0.096 0.64-0.032l7.616-5.088c0.192-0.128 0.288-0.32 0.288-0.544s-0.096-0.416-0.288-0.544l-7.584-5.088c-0.096-0.064-0.224-0.096-0.352-0.096z"
        ></path>
        <path
          d="M16 0.32c-8.64 0-15.68 7.040-15.68 15.68s7.040 15.68 15.68 15.68 15.68-7.040 15.68-15.68-7.040-15.68-15.68-15.68zM16 29.216c-7.296 0-13.216-5.92-13.216-13.216s5.92-13.216 13.216-13.216 13.216 5.92 13.216 13.216-5.92 13.216-13.216 13.216z"
        ></path>
        <path
          d="M16 32c-8.832 0-16-7.168-16-16s7.168-16 16-16 16 7.168 16 16-7.168 16-16 16zM16 0.672c-8.448 0-15.328 6.88-15.328 15.328s6.88 15.328 15.328 15.328c8.448 0 15.328-6.88 15.328-15.328s-6.88-15.328-15.328-15.328zM16 29.568c-7.488 0-13.568-6.080-13.568-13.568s6.080-13.568 13.568-13.568c7.488 0 13.568 6.080 13.568 13.568s-6.080 13.568-13.568 13.568zM16 3.104c-7.104 0-12.896 5.792-12.896 12.896s5.792 12.896 12.896 12.896c7.104 0 12.896-5.792 12.896-12.896s-5.792-12.896-12.896-12.896z"
        ></path>
      </symbol>
      <symbol id="icon-next" viewBox="0 0 32 32">
        <title>Next</title>
        <path
          d="M2.304 18.304h14.688l-4.608 4.576c-0.864 0.864-0.864 2.336 0 3.232 0.864 0.864 2.336 0.864 3.232 0l8.448-8.48c0.864-0.864 0.864-2.336 0-3.232l-8.448-8.448c-0.448-0.448-1.056-0.672-1.632-0.672s-1.184 0.224-1.632 0.672c-0.864 0.864-0.864 2.336 0 3.232l4.64 4.576h-14.688c-1.248 0-2.304 0.992-2.304 2.272s1.024 2.272 2.304 2.272z"
        ></path>
        <path
          d="M29.696 26.752c1.248 0 2.304-1.024 2.304-2.304v-16.928c0-1.248-1.024-2.304-2.304-2.304s-2.304 1.024-2.304 2.304v16.928c0.064 1.28 1.056 2.304 2.304 2.304z"
        ></path>
      </symbol>
      <symbol id="icon-prev" viewBox="0 0 32 32">
        <title>Previous</title>
        <path
          d="M29.696 13.696h-14.688l4.576-4.576c0.864-0.864 0.864-2.336 0-3.232-0.864-0.864-2.336-0.864-3.232 0l-8.448 8.48c-0.864 0.864-0.864 2.336 0 3.232l8.448 8.448c0.448 0.448 1.056 0.672 1.632 0.672s1.184-0.224 1.632-0.672c0.864-0.864 0.864-2.336 0-3.232l-4.608-4.576h14.688c1.248 0 2.304-1.024 2.304-2.304s-1.024-2.24-2.304-2.24z"
        ></path>
        <path
          d="M2.304 5.248c-1.248 0-2.304 1.024-2.304 2.304v16.928c0 1.248 1.024 2.304 2.304 2.304s2.304-1.024 2.304-2.304v-16.928c-0.064-1.28-1.056-2.304-2.304-2.304z"
        ></path>
      </symbol>

app/views/songs/_song_item.html.slim
tr id="song-#{song.id}"
  td = song.id
  td = song.name
  td = song.author
  td = audio_tag song.url, controls: true
  td = image_tag song.cover, width: 100
  td = link_to "Edit", edit_song_path(song),
    class: "text-decoration-none", remote: true

app/views/songs/_song_modal.html.slim
#song-modal.modal.fade.song-modal tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true"
  .modal-dialog.modal-dialog-centered
    .modal-content
      .modal-header
        h5#song-modal-title.modal-title
        button.btn-close type="button" data-bs-dismiss="modal" aria-label="Close"
      .modal-body
        #song-modal-body

app/views/songs/create.js.slim
| $("#song-modal").modal("hide");
| $("#list-song").prepend("
= j render "song_item", song: @song
| ");

|
  Toast.fire({
    icon: "success",
    title: "Song was created successfully!"
  });

app/views/songs/edit.js.slim
| $("#song-modal").modal("show");
| $("#song-modal-title").text("Edit song");
| $("#song-modal-body").html("
= j render "form", song: @song
| ");

app/views/songs/index.html.slim
- provide :title, "My Playlist"
.songs
  = link_to "Add new song", new_song_path, class: "btn mb-3 add-new-song-button", remote: true
  = render "list_song", songs: @songs
  = render "song_modal"

app/views/songs/new.js.slim
| $("#song-modal").modal("show");
| $("#song-modal-title").text("New song");
| $("#song-modal-body").html("
= j render "form", song: @song
| ");

app/views/songs/songs.html.slim
- provide :title, "My Playlist"
#song-frame
  = render "song_frame", song: @song

app/views/songs/songs.js.slim
| $("#song-frame").html("
= j render "song_frame", song: @song
| ");

app/views/songs/update.js.slim
| $("#song-modal").modal("hide");
| $("#song-#{@song.id}").replaceWith("
= j render "song_item", song: @song
| ");

|
  Toast.fire({
    icon: "success",
    title: "Song was updated successfully!"
  });