config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "about-me", to: "static_pages#about"
  get "emoticons", to: "static_pages#emoticon"
  get "favorite-songs", to: "songs#songs"

  resources :posts, param: :slug do
    member do
      put :vote
      put :unvote
    end
  end
  resources :tags, param: :slug, only: %i(show)
  resources :songs, except: :destroy
  resources :skills

  match "/404", to: "errors#render404", via: :all
  match "/422", to: "errors#render422", via: :all
  match "/500", to: "errors#render500", via: :all
end

app/views/shared/about/_about_title.html.slim
.about__title.text-center
  hr
  .title__name.py-4 = title
  hr

app/views/shared/about/_card_infor.html.slim
.card__infor
  .card-body.d-flex.justify-content-center
    img.img-thumbnail.rounded-circle.avatar src="https://res.cloudinary.com/phucdx/image/upload/v1615006143/wataridori/images/avatar_yvycdo.jpg" alt="avatar"
    .infor
      h3.admin__name Phuc Dang Xuan
      p 頑張れば、何でもできる。
      .social__link
        a href="https://www.linkedin.com/in/wataridori/" title="Linkedin" target="_blank"
          i.fab.fa-linkedin
        a href="https://join.skype.com/invite/VRcIelfuGH2Y" title="Skype" target="_blank"
          i.fab.fa-skype
        a href="https://github.com/dangxuanphuc/" title="Github" target="_blank"
          i.fab.fa-github
        a href="https://www.facebook.com/wataridori.natsumi/" title="Facebook" target="_blank"
          i.fab.fa-facebook
        a href="https://www.instagram.com/wataridori.natsumi/" title="Instagram" target="_blank"
          i.fab.fa-instagram

app/views/shared/about/_education_work.html.slim
.education__work
  .container
    .row
      .col-md-12
        .main-timeline
          .timeline
            .timeline-icon <i class="fas fa-school"></i>
            span.year 2009 - 2013
            .timeline-content
              h5.title Phan Boi Chau Secondary School
              p.description
                | Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quibusdam sequi itaque natus asperiores distinctio qui vitae consequatur sunt ullam repellat.
          .timeline
            .timeline-icon <i class="fas fa-school"></i>
            span.year 2013 - 2016
            .timeline-content
              h5.title Tu Ky High School
              p.description
                | Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam unde debitis dolores accusantium dolorem iure magnam non sed dolor consequuntur.
          .timeline
            .timeline-icon <i class="fas fa-university"></i>
            span.year 2016 - 2020
            .timeline-content
              h5.title VNU University of Science
              p.description
                | Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus eligendi sequi cupiditate provident ipsum at, similique reiciendis repellendus quidem animi.
          .timeline
            .timeline-icon <i class="fa fa-briefcase"></i>
            span.year 12/2020 - 04/2022
            .timeline-content
              h5.title Work with Joy Vietnam
              p.description
                | Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi inventore, voluptatem quas pariatur repellat blanditiis necessitatibus natus sequi non totam.
          .timeline
            .timeline-icon <i class="fas fa-briefcase"></i>
            span.year 06/2022 - Present
            .timeline-content
              h5.title Vareal Vietnam
              p.description
                | Sed eget elementum nisi. Aliquam dapibus nulla nec scelerisque rhoncus. Mauris sagittis, mi nec euismod euismod, lorem magna scelerisque magna, sit amet maximus magna tortor vitae leo.

app/views/shared/about/_favorites.html.slim
.favorites
  nav
    #nav-tab.nav-tabs.d-flex.justify-content-center role="tablist"
      a.tablinks#single-tab onclick="openTab(event, 'singers')" Singer
      a.tablinks onclick="openTab(event, 'songs')" Music
      a.tablinks onclick="openTab(event, 'other')" Other

  #singers.tabcontent
    - favorite_singers.each do |singer|
      .singer__item
        = image_tag "", data: { src: singer.image }, class: "lazy"
        .favorite__name
          .text = singer.name

  #songs.tabcontent
    - favorite_songs.each do |song|
      .song__item
        = image_tag "", data: { src: song.image }, class: "lazy"
        .favorite__name
          .text = song.name

  #other.tabcontent
    - favorite_others.each do |other|
      .other__item
        = image_tag "", data: { src: other.image }, class: "lazy"
        .favorite__name
          .text = other.name

javascript:
  function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
  }

  document.getElementById("single-tab").click();

app/views/shared/about/_skill.html.slim
.skills
  - if current_user
    = link_to "Skills list", skills_path, class: "skills__edit_btn", remote: true
  = render "shared/about/skill_language", skill_language: skill_language
  #skill-tech-box
    = render "shared/about/skill_tech", skill_technology: skill_technology
  = render "skills/skill_modal"
  = render "skills/skill_item_modal"

app/views/shared/about/_skill_language.html.slim
.skill__language.d-flex.justify-content-evenly
  - skill_language.each do |skill|
    .progress.mx-auto data-value="#{skill.percent}"
      span.progress-left
        span.progress-bar
      span.progress-right
        span.progress-bar
      .progress-title.w-100.h-100.rounded-circle.d-flex.align-items-center.justify-content-center
        h5 = skill.name

app/views/shared/about/_skill_tech.html.slim
.skill__tech.d-flex.justify-content-between
  - skill_technology.each do |skill|
    .tech__skill
      .skill__name = skill.name
      .progress
        .progress-bar role="progressbar" style="width: #{skill.percent}%" aria-valuenow="#{skill.percent}" aria-valuemin="0" aria-valuemax="100"

app/views/shared/about/_tech_love.html.slim
.tech__love.d-flex.justify-content-center
  img.tech__image alt="vuejs" title="Vue JS" src="https://res.cloudinary.com/phucdx/image/upload/v1625496993/wataridori/images/vue-js_gidfgl.png"
  img.tech__image alt="rails" title="Ruby on Rails" src="https://res.cloudinary.com/phucdx/image/upload/v1615003949/wataridori/images/rails_rnksqt.png"
  img.tech__image alt="linux" title="Linux" src="https://res.cloudinary.com/phucdx/image/upload/v1625465622/wataridori/images/linux_nccbic.png"