config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#index"
  get "about-me", to: "static_pages#about"
  get "emoticons", to: "static_pages#emoticon"
  get "favorite-songs", to: "songs#songs"

  resources :posts, param: :slug do
    member do
      put :vote
      put :unvote
    end
  end
  resources :tags, param: :slug, only: %i(show)
  resources :songs, except: :destroy
  resources :skills

  match "/404", to: "errors#render404", via: :all
  match "/422", to: "errors#render422", via: :all
  match "/500", to: "errors#render500", via: :all
end

app/views/layouts/_back_to_top.html.slim
.back-to-top.js-back-to-top
  .back-to-top__btn
    i

app/views/layouts/_footer.html.slim
.footer__card.text-center
  #particles-js
  .container
    .footer__start.d-flex.justify-content-evenly
      a.social__link.d-flex.align-items-center.justify-content-center href="https://www.linkedin.com/in/wataridori/" target="_blank"
        i.fab.fa-linkedin
        | LinkedIn
      a.social__link.d-flex.align-items-center.justify-content-center href="https://join.skype.com/invite/VRcIelfuGH2Y" target="_blank"
        i.fab.fa-skype
        | Skype
      a.social__link.d-flex.align-items-center.justify-content-center href="https://github.com/dangxuanphuc/" target="_blank"
        i.fab.fa-github
        | Github
      a.social__link.d-flex.align-items-center.justify-content-center href="https://www.facebook.com/wataridori.natsumi/" target="_blank"
        i.fab.fa-facebook
        | Facebook
      a.social__link.d-flex.align-items-center.justify-content-center href="https://www.instagram.com/wataridori.natsumi/" target="_blank"
        i.fab.fa-instagram
        | Instagram
    hr
    .footer__between.d-flex.justify-content-center
      = link_to "About me", about_me_path
      = link_to "My Playlist", favorite_songs_path
      = link_to "Japanese", tag_path(slug: "nihongo")
      = link_to "IT", tag_path(slug: "it")
    hr
    .footer__end
      - if current_user.present?
        | &copy; 2021 Wataridori's Blog. All Rights Reserved.
      - else
        | &copy; 2021 #{link_to "Wataridori's Blog", new_user_session_path}. All Rights Reserved.

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-md.fixed-top
  .container
    = link_to "Wataridori Blog", root_path, class: "d-flex align-items-center navbar-brand"
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-md-0
        li.nav-item
          = link_to "Home", root_path,
            class: "d-flex align-items-center nav-link #{active_class("static_pages", "index")}"
        li.nav-item
          = link_to "About me", about_me_path,
            class: "d-flex align-items-center nav-link #{active_class("static_pages", "about")}"
        li.nav-item
          = link_to "My Playlist", favorite_songs_path,
            class: "d-flex align-items-center nav-link #{active_class("songs", "songs")}"
        - if user_signed_in?
          li.nav-item
            = link_to "Songs", songs_path,
              class: "d-flex align-items-center nav-link #{active_class("songs", "index")}"
          li.nav-item
            = link_to "Emoticons", emoticons_path,
              class: "d-flex align-items-center nav-link #{active_class("static_pages", "emoticon")}"
      .d-flex.nav__option
        - if user_signed_in?
          = link_to new_post_path, class: "btn d-flex align-items-center create__post" do
            i.fas.fa-pencil-alt Create Post
        button.btn.btn-light.rounded-circle.ms-2.switch__theme.js--switch-theme
          i#light.fas.fa-moon class="#{ 'd-none' if cookies[:theme] == 'dark' }"
          i#dark.fas.fa-sun class="#{ 'd-none' if cookies[:theme] == 'light' || cookies[:theme].nil? }"

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title = full_title yield :title
    meta name="keywords" content="Wataridori's Blog"
    meta name="author" content="Phuc Dang Xuan"
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_pack_tag "application", "data-turbolinks-track": "reload"
    = favicon_link_tag "favicon.ico"
    link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"
    link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@200;300;400;500&display=swap" rel="stylesheet"
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer"
    = tag :meta, property: "og:site_name", content: "Wataridori's Blog"

    - if params[:controller] == "posts"
      = yield :head
    - else
      = display_meta_tags(default_meta_tags)

  body class="#{ 'dark-theme' if cookies[:theme] == 'dark' }"
    = render "layouts/back_to_top"
    = render "layouts/navbar"
    .container
      = yield
    = render "layouts/footer" if show_footer(params)
    script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"
    = javascript_pack_tag "particles"